/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A resident Hearth engine: shared warm caches, warm shells, and profiler.
 *
 * Construct one per process and keep it; the caches only pay off while it
 * lives. Dropping it stops the optimizer and kills every pooled shell.
 */
export declare class HearthEngine {
  constructor(options?: EngineOptions | undefined | null)
  /** Enable the profiler (timing + allocation tracking). */
  enableProfiler(): void
  /** The profiler report as text. */
  stats(): string
  read(params: ReadParams): ReadResult
  readAsync(params: ReadParams, signal?: AbortSignal): Promise<ReadResult>
  /**
   * Read a file's raw bytes as a Node `Buffer` — binary-safe, and it skips
   * the UTF-8 string construction `read` does.
   */
  readBytes(params: ReadParams): Buffer
  readBytesAsync(params: ReadParams, signal?: AbortSignal): Promise<Buffer>
  write(params: WriteParams): WriteResult
  /**
   * Fast write: `path` and `content` are passed directly, so the string is
   * **moved** into the cache — one fewer full-content copy than `write`.
   */
  writeFast(path: string, content: string): WriteResult
  writeAsync(params: WriteParams, signal?: AbortSignal): Promise<WriteResult>
  edit(params: EditParams): EditResult
  /**
   * Apply several disjoint replacements to one file in one atomic commit.
   * Each `oldText` is matched against the original file, not against the
   * result of an earlier edit in the same call.
   */
  editBatch(params: EditBatchParams): EditBatchResult
  editBatchAsync(params: EditBatchParams, signal?: AbortSignal): Promise<EditBatchResult>
  /** Synchronous grep. Prefer `grepAsync` for large trees. */
  grep(params: GrepParams): GrepResult
  grepAsync(params: GrepParams, signal?: AbortSignal): Promise<GrepResult>
  /**
   * Synchronous bash. Blocks the event loop for the command's whole
   * duration; prefer `bashAsync` or `bashStream`.
   */
  bash(params: BashParams): BashResult
  bashAsync(params: BashParams, signal?: AbortSignal): Promise<BashResult>
  /**
   * Run a command, delivering ordered output chunks to `onChunk` while it
   * runs. A timeout or an abort still resolves, with the partial output and
   * `timedOut`/`aborted` set, so a caller keeps what it already rendered.
   */
  bashStream(params: BashParams, onChunk: (chunk: BashChunk) => void, signal?: AbortSignal): Promise<BashResult>
  /**
   * Drop `path` from the file cache and any walk that could have enumerated
   * it. Use after a mutation Hearth did not perform itself.
   */
  invalidatePath(path: string): InvalidateResult
  /**
   * Drop everything cached at or beneath `root`.
   *
   * This is the conservative hammer to reach for after a shell command: an
   * arbitrary command can create, delete, rename or rewrite anything under
   * its cwd, and no cheaper invalidation is sound.
   */
  invalidateRoot(root: string): InvalidateResult
  /** The scoped form: pick recursion and which caches to touch. */
  invalidate(path: string, recursive?: boolean | undefined | null, scope?: CacheScope | undefined | null): InvalidateResult
  /** Drop every cached file and walk. */
  clearCaches(): InvalidateResult
}

/** Which pipe a streamed chunk came from. */
export declare const enum BashChannel {
  Stdout = 'stdout',
  Stderr = 'stderr'
}

/**
 * One streamed slice of command output. `seq` is a single monotonic counter
 * shared by both channels, so replaying chunks in `seq` order reproduces the
 * order Hearth observed the bytes in.
 */
export interface BashChunk {
  seq: number
  channel: BashChannel
  /** UTF-8 text. Multi-byte sequences are never split across chunks. */
  text: string
}

export interface BashParams {
  command: string
  /** Working directory. Defaults to the engine's cwd. */
  cwd?: string
  /** Hard timeout in milliseconds. Defaults to the engine's. */
  timeoutMs?: number
  /** Extra environment variables for this command only. */
  env?: Record<string, string>
  /**
   * Start from an empty environment instead of inheriting. Ignored in
   * warm-shell mode, which always extends the pooled shell's environment.
   */
  envClear?: boolean
  /** Shell to run under. Defaults to the engine's, then `/bin/sh -c`. */
  shell?: ShellSpec
  /**
   * Accumulate the full output into the result. Defaults to true; turn it
   * off when only consuming the stream.
   */
  collectOutput?: boolean
}

export interface BashResult {
  /** Everything written to stdout; empty when `collectOutput` was off. */
  stdout: string
  /** Everything written to stderr; empty when `collectOutput` was off. */
  stderr: string
  /** Exit code, or -1 when the command was signalled. */
  exitCode: number
  /** The signal that killed the process, when it was signalled. */
  signal?: number
  /** True when the command was killed for exceeding its timeout. */
  timedOut: boolean
  /**
   * True when the caller's `AbortSignal` killed it. The partial output is
   * still returned rather than thrown away.
   */
  aborted: boolean
  durationUs: number
  /** How many chunks were delivered to the stream callback. */
  chunks: number
}

/** Which caches an invalidation should drop. */
export declare const enum CacheScope {
  Files = 'files',
  Walks = 'walks',
  All = 'all'
}

/**
 * A changed region plus its context. The gap between one hunk's end and the
 * next hunk's start is exactly the number of unchanged lines a renderer elides.
 */
export interface DiffHunk {
  oldStart: number
  oldLines: number
  newStart: number
  newLines: number
  rows: Array<DiffRow>
}

/** What one row of a diff hunk does. */
export declare const enum DiffOp {
  Equal = 'equal',
  Insert = 'insert',
  Delete = 'delete'
}

/** One line of a diff hunk, without its terminator. */
export interface DiffRow {
  op: DiffOp
  /** 1-based line in the pre-edit content; absent for inserts. */
  oldLine?: number
  /** 1-based line in the post-edit content; absent for deletes. */
  newLine?: number
  text: string
}

export interface EditBatchParams {
  path: string
  /**
   * At least one replacement. Each is matched against the original file, not
   * against the result of an earlier edit in the same call.
   */
  edits: Array<EditReplacement>
  /** Unchanged lines kept around each change in `hunks`. Defaults to 4. */
  diffContext?: number
  /** Skip diff computation; `hunks` comes back empty. */
  skipDiff?: boolean
  /** Also return the full post-edit content. */
  returnContent?: boolean
  /** Defaults to `atomic`. */
  mode?: WriteMode
  /** Edit a symlink's target instead of replacing the link. Defaults to true. */
  followSymlinks?: boolean
}

export interface EditBatchResult {
  /** The path actually written, after symlink resolution. */
  path: string
  replacements: number
  byteLen: number
  /** True when at least one edit only matched after normalization. */
  usedNormalizedFallback: boolean
  /** True when the file started with a UTF-8 BOM (preserved). */
  hadBom: boolean
  /** True when the file's line endings were CRLF (preserved). */
  crlf: boolean
  /**
   * Line count of the pre-edit content, counting the empty element after a
   * trailing newline (the count a newline split yields).
   */
  oldLineCount: number
  /** Line count of the post-edit content, counted the same way. */
  newLineCount: number
  /** 1-based line in the post-edit content where the first change appears. */
  firstChangedLine?: number
  hunks: Array<DiffHunk>
  /** Present only when `returnContent` was set. */
  content?: string
}

export interface EditParams {
  path: string
  oldString: string
  newString: string
  /** Replace every occurrence instead of requiring a unique match. */
  replaceAll?: boolean
}

/**
 * One targeted replacement. `oldText` must be unique in the original file and
 * must not overlap another edit's target.
 */
export interface EditReplacement {
  oldText: string
  newText: string
}

export interface EditResult {
  replacements: number
  byteLen: number
}

/** Construction options for a [`crate::HearthEngine`]. */
export interface EngineOptions {
  /** Working directory relative paths resolve against, and `bash`'s default. */
  cwd?: string
  /** Threads used by the parallel directory walker and by `grep`. */
  walkThreads?: number
  /** Watch searched roots and invalidate caches from filesystem events. */
  enableWatch?: boolean
  /** Run the background cache-tuning loop. */
  enableOptimizer?: boolean
  /**
   * Skip the per-hit freshness `stat` on warm reads. Single-writer fast path:
   * changes made outside Hearth stay cached until explicitly invalidated.
   */
  trustCache?: boolean
  /** Use the pooled warm shell for `bash`. */
  warmShell?: boolean
  /** Hard cap on the number of files kept warm. */
  maxCachedFiles?: number
  /** Default `bash` timeout in milliseconds. */
  bashTimeoutMs?: number
  /** Default shell for `bash`. Per-call `shell` overrides this. */
  shell?: ShellSpec
}

export interface FileMatches {
  path: string
  matchCount: number
  /** Matching and context lines; empty outside `content` mode. */
  lines: Array<GrepLine>
}

export interface GrepLine {
  lineNumber: number
  /** The line text, without its terminator. */
  text: string
  /** True for a match, false for a context line. */
  isMatch: boolean
}

/** Output shape for `grep`. */
export declare const enum GrepMode {
  FilesWithMatches = 'filesWithMatches',
  Content = 'content',
  Count = 'count'
}

export interface GrepParams {
  /** Regular expression, or a literal when `fixedStrings` is set. */
  pattern: string
  /** Root to search. A file searches just that file. */
  path: string
  /** Defaults to `filesWithMatches`. */
  mode?: GrepMode
  /** Restrict to paths matching any of these globs. */
  globs?: Array<string>
  caseInsensitive?: boolean
  /** Case-insensitive unless the pattern contains an uppercase letter. */
  smartCase?: boolean
  fixedStrings?: boolean
  multiline?: boolean
  /** Context lines before each match (`content` mode only). */
  beforeContext?: number
  /** Context lines after each match (`content` mode only). */
  afterContext?: number
  /** Stop after this many matches per file. */
  maxCount?: number
  /**
   * Stop after this many matches across all files. The kept matches are the
   * first `maxTotalCount` in path order, independent of scheduling.
   */
  maxTotalCount?: number
  /** Search hidden files and directories. */
  hidden?: boolean
  /** Honour `.gitignore`/`.ignore`. Defaults to true. */
  respectGitignore?: boolean
  followSymlinks?: boolean
}

export interface GrepResult {
  /** Per-file results, sorted by path. */
  files: Array<FileMatches>
  totalMatches: number
  filesSearched: number
  walkCacheHit: boolean
  /** True when `maxTotalCount` capped the result; more matches exist. */
  limitReached: boolean
  /** The resolved search root. */
  root: string
  rootIsDir: boolean
}

export interface InvalidateResult {
  filesInvalidated: number
  walksInvalidated: number
}

/** How a line window is cut out of a file. */
export declare const enum LineWindowMode {
  /**
   * `cat`-style: the window keeps the newline that ends its last line, and a
   * trailing newline adds no phantom line to `totalLines`.
   */
  Slice = 'slice',
  /**
   * Newline-split style: the file is split on newlines and the selected
   * elements are re-joined, so a window never ends with a newline and a
   * trailing newline yields a final empty element.
   */
  SplitLines = 'splitLines'
}

export interface ReadParams {
  /** Path to read. Relative paths resolve against the engine's cwd. */
  path: string
  /** 1-based line to start from. */
  offset?: number
  /** Maximum number of lines to return. */
  limit?: number
  /** Prefix each returned line with its number, like `cat -n`. */
  lineNumbers?: boolean
  /** How the window is cut. Defaults to `slice`. */
  lineMode?: LineWindowMode
}

export interface ReadResult {
  content: string
  /** Total lines in the file, counted per `lineMode`. */
  totalLines: number
  returnedLines: number
  byteLen: number
  /** True when `offset`/`limit` clipped the content. */
  truncated: boolean
  /** True when the file looks binary; `content` is then empty. */
  binary: boolean
  /** True when this came from the warm cache. */
  cacheHit: boolean
  /** Whether the underlying file ends with a newline. */
  endsWithNewline: boolean
}

/** The shell a `bash` call runs under. */
export interface ShellSpec {
  /** Executable to spawn, e.g. `/bin/bash`. */
  program: string
  /** Arguments before the command, e.g. `["-c"]`. */
  args?: Array<string>
  /** How the command is handed over. Defaults to `arg`. */
  transport?: ShellTransport
}

/** How a command reaches the shell process. */
export declare const enum ShellTransport {
  /** Appended as a final argv entry, e.g. `bash -c '<command>'`. */
  Arg = 'arg',
  /** Written to the shell's stdin, e.g. `bash -s`. */
  Stdin = 'stdin'
}

/** How `write` puts bytes on disk. */
export declare const enum WriteMode {
  /** Crash-safe temp file + rename. Replaces the target inode. */
  Atomic = 'atomic',
  /** Truncate and rewrite the existing inode, like `fs.writeFile`. */
  InPlace = 'inPlace'
}

export interface WriteParams {
  path: string
  content: string
  /** Create missing parent directories. Defaults to true. */
  createDirs?: boolean
  /** Defaults to `atomic`. */
  mode?: WriteMode
  /** Write through a symlink instead of replacing it. Defaults to true. */
  followSymlinks?: boolean
}

export interface WriteResult {
  bytesWritten: number
  /** True when the file already existed. */
  existed: boolean
  /** The path actually written, after symlink resolution. */
  path: string
  followedSymlink: boolean
}
