import assert from "node:assert/strict";
import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";

import {
  inspectGeneratedLoader,
  stageNapiBuildBindings,
  verifyNapiReleaseVersions,
} from "./verify-napi-release-versions.mjs";

const VERSION = "1.2.3-rc.1";
const PLATFORMS = [
  ["darwin-arm64", "@hearthdev/napi-darwin-arm64"],
  ["linux-x64-gnu", "@hearthdev/napi-linux-x64-gnu"],
];
const TARGETS = ["aarch64-apple-darwin", "x86_64-unknown-linux-gnu"];
const TYPES = "export declare const binding: unknown\n";

function loaderSource({
  comparisonVersions = PLATFORMS.map(() => VERSION),
  messageVersions = comparisonVersions,
  packages = PLATFORMS.map(([, name]) => name),
} = {}) {
  return `/* auto-generated by NAPI-RS */
import { createRequire } from 'module'
${packages
  .map(
    (packageName, index) => `const bindingPackageVersion = require('${packageName}/package.json').version
if (bindingPackageVersion !== '${comparisonVersions[index]}' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
  throw new Error(\`Native binding package version mismatch, expected ${messageVersions[index]} but got \${bindingPackageVersion}. You can reinstall dependencies to fix this issue.\`)
}`,
  )
  .join("\n")}
`;
}

async function writeJson(path, value) {
  await writeFile(path, `${JSON.stringify(value, null, 2)}\n`);
}

async function fixture(t, {
  rootVersion = VERSION,
  loader = loaderSource(),
  platformVersions = {},
  optionalDependencies,
} = {}) {
  const root = await mkdtemp(join(tmpdir(), "hearth-release-versions-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const packageDir = join(root, "package");
  const artifactsDir = join(root, "artifacts");
  const platformNames = PLATFORMS.map(([, name]) => name);
  const rootManifest = {
    name: "@hearthdev/napi",
    version: rootVersion,
    napi: { targets: TARGETS },
    optionalDependencies:
      optionalDependencies ?? Object.fromEntries(platformNames.map((name) => [name, rootVersion])),
  };
  await mkdir(join(packageDir, "npm"), { recursive: true });
  await mkdir(artifactsDir, { recursive: true });
  await writeJson(join(packageDir, "package.json"), rootManifest);
  await writeFile(join(packageDir, "index.js"), loader);
  await writeFile(join(packageDir, "index.d.ts"), TYPES);
  for (const [directory, name] of PLATFORMS) {
    await mkdir(join(packageDir, "npm", directory), { recursive: true });
    await writeJson(join(packageDir, "npm", directory, "package.json"), {
      name,
      version: platformVersions[name] ?? rootVersion,
    });
  }
  for (const target of TARGETS) {
    await mkdir(join(artifactsDir, `bindings-${target}`), { recursive: true });
    await writeFile(join(artifactsDir, `bindings-${target}`, "index.js"), loaderSource());
    await writeFile(join(artifactsDir, `bindings-${target}`, "index.d.ts"), TYPES);
  }
  return { artifactsDir, packageDir };
}

test("accepts one exact version across loader and package graph", async (t) => {
  const { packageDir } = await fixture(t);
  assert.deepEqual(await verifyNapiReleaseVersions(packageDir), {
    version: VERSION,
    platformPackages: 2,
    loaderGuards: 2,
  });
});

test("recognizes every guard in the checked-in generated ESM loader", async () => {
  const packageDir = new URL("../crates/hearth-napi/", import.meta.url);
  const [manifest, loader] = await Promise.all([
    readFile(new URL("package.json", packageDir), "utf8").then(JSON.parse),
    readFile(new URL("index.js", packageDir), "utf8"),
  ]);
  const checks = inspectGeneratedLoader(loader, manifest.version, [
    "@hearthdev/napi-darwin-arm64",
    "@hearthdev/napi-darwin-x64",
    "@hearthdev/napi-linux-arm64-gnu",
    "@hearthdev/napi-linux-x64-gnu",
  ]);
  assert.equal(checks.length, 26);
});

test("stages byte-identical generated bindings from every target", async (t) => {
  const { artifactsDir, packageDir } = await fixture(t, { loader: loaderSource({ comparisonVersions: ["0.1.0", "0.1.0"] }) });
  const summary = await stageNapiBuildBindings(packageDir, artifactsDir);
  assert.deepEqual(summary, {
    version: VERSION,
    targets: 2,
    canonicalTarget: TARGETS[0],
  });
  assert.equal(await readFile(join(packageDir, "index.js"), "utf8"), loaderSource());
});

test("rejects target-specific loader drift", async (t) => {
  const { artifactsDir, packageDir } = await fixture(t);
  await writeFile(
    join(artifactsDir, `bindings-${TARGETS[1]}`, "index.js"),
    `${loaderSource()}\n`,
  );
  await assert.rejects(
    stageNapiBuildBindings(packageDir, artifactsDir),
    /index\.js differs between aarch64-apple-darwin and x86_64-unknown-linux-gnu/,
  );
});

test("rejects generated declarations that differ from the committed API", async (t) => {
  const { artifactsDir, packageDir } = await fixture(t);
  await writeFile(join(packageDir, "index.d.ts"), "export declare const changed: true\n");
  await assert.rejects(
    stageNapiBuildBindings(packageDir, artifactsDir),
    /generated index\.d\.ts .* differs from the committed file/,
  );
});

test("rejects stale loader comparisons and messages", async (t) => {
  const staleGuard = await fixture(t, {
    loader: loaderSource({ comparisonVersions: [VERSION, "1.2.2"] }),
  });
  await assert.rejects(
    verifyNapiReleaseVersions(staleGuard.packageDir),
    /expects 1\.2\.2, root package is 1\.2\.3-rc\.1/,
  );

  const staleMessage = await fixture(t, {
    loader: loaderSource({ messageVersions: [VERSION, "1.2.2"] }),
  });
  await assert.rejects(
    verifyNapiReleaseVersions(staleMessage.packageDir),
    /compares 1\.2\.3-rc\.1 but reports 1\.2\.2/,
  );
});

test("fails closed when the generated loader template drifts", async (t) => {
  const malformed = loaderSource().replace("bindingPackageVersion !==", "bindingPackageVersion !=");
  const { packageDir } = await fixture(t, { loader: malformed });
  await assert.rejects(
    verifyNapiReleaseVersions(packageDir),
    /generated loader template drift/,
  );
});

test("rejects a platform manifest version mismatch", async (t) => {
  const { packageDir } = await fixture(t, {
    platformVersions: { "@hearthdev/napi-linux-x64-gnu": "1.2.2" },
  });
  await assert.rejects(
    verifyNapiReleaseVersions(packageDir),
    /platform package @hearthdev\/napi-linux-x64-gnu is 1\.2\.2/,
  );
});

test("requires exact optionalDependencies matching every platform package", async (t) => {
  const ranged = await fixture(t, {
    optionalDependencies: {
      "@hearthdev/napi-darwin-arm64": VERSION,
      "@hearthdev/napi-linux-x64-gnu": `^${VERSION}`,
    },
  });
  await assert.rejects(
    verifyNapiReleaseVersions(ranged.packageDir),
    /uses \^1\.2\.3-rc\.1, expected exact version/,
  );

  const missing = await fixture(t, {
    optionalDependencies: { "@hearthdev/napi-darwin-arm64": VERSION },
  });
  await assert.rejects(
    verifyNapiReleaseVersions(missing.packageDir),
    /optionalDependencies .* do not match platform packages/,
  );
});

test("requires every platform package to have a loader guard", async (t) => {
  const { packageDir } = await fixture(t, {
    loader: loaderSource({
      comparisonVersions: [VERSION],
      messageVersions: [VERSION],
      packages: [PLATFORMS[0][1]],
    }),
  });
  await assert.rejects(
    verifyNapiReleaseVersions(packageDir),
    /generated loader has no version check for @hearthdev\/napi-linux-x64-gnu/,
  );
});

test("rejects non-exact root versions", async (t) => {
  const { packageDir } = await fixture(t, { rootVersion: `^${VERSION}` });
  await assert.rejects(
    verifyNapiReleaseVersions(packageDir),
    /root package version is not an exact SemVer/,
  );
});

test("runs installed-package suites only after GITHUB_ENV becomes visible", async () => {
  const workflow = await readFile(
    new URL("../.github/workflows/release.yml", import.meta.url),
    "utf8",
  );
  const install = workflow.indexOf("run: bash scripts/verify-tarball.sh");
  const suiteStep = workflow.indexOf("- name: Verify the installed tarball on Node and Bun");
  const installedSmoke = workflow.indexOf("node crates/hearth-napi/smoke.mjs", suiteStep);
  assert.ok(install >= 0, "release workflow must install the packed package");
  assert.ok(suiteStep > install, "installed suites must run in a later GitHub Actions step");
  assert.ok(installedSmoke > suiteStep, "the later step must exercise the installed entry point");
});
